source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '13.0'

target 'STEventSource_Example' do
  pod 'STEventSource', :path => '../'

  target 'STEventSource_Tests' do
    inherit! :search_paths

    
  end
end
